### ISSUE TITLE
Set-AzureADUser - setting null value for attribute

### ISSUE THREAD

**Issue by akemball** [Azure/azure-docs-powershell-azuread#166]
With the Set-MsolUser cmdlet, it is possible to set an attribute to "$null" to clear the value. E.g.
Set-Msoluser -userprincipalname <upn-of-user> -Mobile "$null"  will clear whatever value is present for the Mobile phone.

But  Set-AzureADUser -objectid <upn-of-user> -Mobile "$null" will generate an error.

set-AzureADUser : Error occurred while executing SetUser
Code: Request_BadRequest
Message: Invalid value specified for property 'mobile' of resource 'User'.
RequestId: e7c1d0eb-de00-4ab7-bf8b-5b7d9efbfa4e
DateTimeStamp: Wed, 15 Nov 2017 12:56:36 GMT
Details: PropertyName  - mobile, PropertyErrorCode  - InvalidLength
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed
At line:1 char:1
..........

Using AzureADPreview 2.0.0.137

Thanks

**Comment by RobdeJong** [comment]
No, this is currently no supported

**Comment by egbertvanderhout** [comment]
So... how do I empty those properties?

**Comment by thuld** [comment]
Are you going to fix this defect? Currently do we need to "remove" values by setting the value to " " which is not perfect

**Comment by RobdeJong** [comment]
Yes, we are planning to fix this in one of our upcoming releases. No timelines to share yet though.

**Comment by RobdeJong** [comment]
We have it in our plan but no eta yet.

**Comment by TiloGit** [comment]
same today with 2.0.1.16

```powershell
Name              : azuread
Path              : C:\Program Files\WindowsPowerShell\Modules\azuread\2.0.1.16\Microsoft.Open.AzureAD16.Graph.PowerShell.dll
Description       : Azure Active Directory V2 General Availability Module.
                    This is the General Availability release of Azure Active Directory V2 PowerShell Module.
                    For detailed information on how to install and run this module from the PowerShell Gallery including prerequisites, please refer to
                    https://msdn.microsoft.com/powershell/gallery/readme
ModuleType        : Binary
Version           : 2.0.1.16
```

**Comment by jecarlsen** [comment]
We're doing this quite often on a number of customers users moving from onprem to Cloud only. We too use " " instead of NULL which still works. 
Please don't break this 'feature' while we're waiting for a valid NULL assignment feature.

**Comment by memonjur** [comment]
"PropertyErrorCode - InvalidLength" is the error. You can set null value for Telephone number. The maximum length is 64. For it the error AAD Graph returns is this and it translates to the error code that powershell displays.

{
   "odata.error":{
      "code":"Request_BadRequest",
      "message":{
         "lang":"en",
         "value":"Invalid value specified for property 'telephoneNumber' of resource 'User'."
      },
      "values":[
         {
            "item":"PropertyName",
            "value":"telephoneNumber"
         },
         {
            "item":"PropertyErrorCode",
            "value":"InvalidLength"
         }
      ]
   }
}

**Comment by memonjur** [comment]
Instead of this:
Set-AzureADUser -ObjectId <objectId> -Mobile **"$null"**

Use this:
Set-AzureADUser -ObjectId <objectId> -Mobile **$null**

**Comment by dougraheem** [comment]
@Terrenus try following, I had similar requirements.

 Set-AzureADUser -ObjectId $line.UserPrincipleName -City " "

Hope it helps.

**Comment by Terrenus** [comment]
@dougraheem It works, kinda...

Unluckily we have a script from the background that recognise " " as a space, and not as a null or empty field.. Which is what I need. I guess I need to wait for an update or something similar from it.

Thanks for the hint :-)

**Comment by sankamm** [comment]
@dougraheem 

any update since 2017?

**Comment by alexandermainz** [comment]
Any news with this issue?

I accidently set the "ImmutableId" field to a value and cannot use the "workaround" and set a white space in this field, because it has to be a unique value for alle AD identites in the tenant...

**Comment by sbgillett** [comment]
Why is this still not possible?

**Comment by emekm** [comment]
after 2 years from the first request the BUG still exists.
It is really strange that we can set null from GUI, but not using remote powershell!

**Comment by rupeshprasad** [comment]
Any update on this? I am too stuck with this and would like to set filed value to null rather than " ".

**Comment by Tiagojaduarte** [comment]
It's been almost 3 years and still not a proper way of clearing the values of AAD user fields?
Common guys...

**Comment by urbantom** [comment]
Still not resolved. Shame you, guys.

**Comment by RikardStrand** [comment]
Encountered this bug today. Is there any ETA on when this will be resolved so we can use AzureAD cmdlets to clear (nullify) a value ? 

Currently I need to make a lot of logic in my scripts to use both cmdlets but in some cases also use Graph API directly. 

📢: @RobdeJong

**Comment by leon-yeung-dragon** [comment]
Also encountered this bug today.  Any ETA on this?

**Comment by lwchkg** [comment]
```
Set-AzureADUser : Error occurred while executing SetUser 
Code: Request_BadRequest
Message: Invalid value specified for property 'surname' of resource 'User'.
RequestId: 482c1001-db45-4e62-973a-4df0c2d4e216
DateTimeStamp: Sat, 05 Sep 2020 01:31:11 GMT
Details: PropertyName  - surname, PropertyErrorCode  - InvalidLength
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed
At D:\Documents\GoogleDrive\azuread\lib\SetUserInfo.ps1:104 char:5
+     Set-AzureADUser `
+     ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-AzureADUser], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.SetUser
```

**Comment by kendrick3d** [comment]
I was able to find the answer to this one after some troubleshooting to make -OtherMails null. I ran into the same issues as above using $null, "$null", and " ", but I was able to modify the value and set it to null by setting the attribute to the following...

Set-AzureAdUser -ObjectID $id -OtherMails @{}

**Comment by iSnackyCracky** [comment]
> I was able to find the answer to this one after some troubleshooting to make -OtherMails null. I ran into the same issues as above using $null, "$null", and " ", but I was able to modify the value and set it to null by setting the attribute to the following...
> 
> Set-AzureAdUser -ObjectID $id -OtherMails @{}

I'm facing basically the same issue as everyone else in this thread but with the FacsimileTelephoneNumber.
`""`, "`$null"` and `$null` don't work (first two generate "BadRequest" error, the last doesn't give an error but won't change the field)
Aetting it to `@{}` changes the field to `System.Collection.Hashtable` (which it is, but that doesn't really help either) :(

**Comment by Tiagojaduarte** [comment]
Why has this issue been closed?
Have you guys fixed this?

**Comment by megharaikwar** [comment]
Please use $Null instead of "$Null" and it should fix the issue.

**Comment by akemball** [comment]
No idea why this was closed - though the same user appeared to close several issues at the same time.
It is now 3 years since I originally raised this issue - and it still does not work. Very frustrating.

**Comment by sankamm** [comment]
@billmath Why has this issue been closed?

**Comment by 54656452** [comment]
@billmath or @RobdeJong: Can we get some insight on why this long-standing issue was closed without a resolution despite previous comments indicating that a future release would resolve the matter?

I am attempting to transition all workflows to AzureAD commands instead of MSOL commands, but the inability to set an AAD attribute to a null value is a significant hurdle.

**Comment by psignoret** [comment]
Hi everyone, just came across this issue myself, and found an approach that might help others around this issue. (Of course, this should only be useful to those who have a compelling reason to keep using the AzureAD module, instead of the [Microsoft Graph PowerShell](https://docs.microsoft.com/graph/powershell/installation) module.)

This workaround makes use of the fact that the `ExtensionProperty` parameter for **Set-AzureADUser**, which was probably intended for directory extensions, can be used to set any (valid) property of the user object. This gets past one of the issue at play here, where properties set to `$null` are not being emitted when the object is serialized to JSON.

```powershell
$properties = [Collections.Generic.Dictionary[[String],[String]]]::new()
$properties.Add("telephoneNumber", [NullString]::Value)
Set-AzureADUser -ObjectId "test@phsignor.onmicrosoft.com" -ExtensionProperty $properties
```

@5465645 I know this is a bit late to be commenting, but if you're doing a migration, you should really look to change to Microsoft Graph PowerShell, instead of Azure AD PowerShell.

**Comment by iSnackyCracky** [comment]
Hi @psignoret,

interesting workaround. It would still be nice to get this fixed properly.

---

Regarding your recommendation to using the **Microsoft Graph** module (_Microsoft Graph PowerShell SDK_):

I don't think this is a proper replacement for the **AzureAD** module (_Azure Active Directory PowerShell for Graph_). At least not for the majority of users or use-cases.
The Graph module is explicitly described as an SDK (Software Development Kit) and is more or less aimed at developers.
There is basically no documentation for the PowerShell module itself (besides how to install it), instead the Graph API and it's functions are documented.

The AzureAD module however is specifically designed to help with or automate administrative tasks.
The average AzureAD (or Microsoft 365) administrator probably doesn't know about the Graph API or how it's permissions (or scopes, as it's called in the documentation) work. (I myself included)

The [_Manage Microsoft 365 with PowerShell_ documentation](https://docs.microsoft.com/en-us/microsoft-365/enterprise/connect-to-microsoft-365-powershell?view=o365-worldwide) also clearly states the AzureAD module is the "recommended" way (over the older **MSOnline** module (_Microsoft Azure Active Directory Module for Windows PowerShell_)) to connect to Microsoft 365 and administer user accouns, groups and licenses. It doesn't even mention the Graph SDK once - which probably has a reason.

Obviously the Graph module definitely has it's use-cases (i.e. for developers creating applications that integrate with M365) but I think the larger part of users (affected by this issue at least) will be admins that just want to automate part of their user management and don't want to get into understanding and working with an API.

**Comment by rossandrewyoung** [comment]
remove-azureaduserextension does the trick

**Comment by stromvirvel** [comment]
@RobdeJong This issue clearly isn't fixed. Please re-open.

**Comment by psignoret** [comment]
@ChrisAtMAF @stromvirvel 
A few things to keep in mind:

1. This repo is for the documentation for the AzureAD module. Issues here are expected to be about the documentation, not about the module itself.
2. That said, I've provided a fairly simple work-around above you can use to set a null value to an attribute: https://github.com/Azure/azure-docs-powershell-azuread/issues/166#issuecomment-824465935
3. The AzureAD module is not going to be getting any updates moving forward. It is strongly recommended for you to start moving to Microsoft Graph PowerShell: https://techcommunity.microsoft.com/t5/azure-active-directory-identity/automate-and-manage-azure-ad-tasks-at-scale-with-the-microsoft/ba-p/1942489

**Comment by nikolai-bravo** [comment]
As of July 2022, trying to set a field to $null still does not do anything. No error, but doesn't change the content of the field either. Attempting to set the field to "" still throws an error as well.

**Comment by me1299** [comment]
Since a few weeks using https://github.com/Azure/azure-docs-powershell-azuread/issues/166#issuecomment-824465935 results in an Internal Server Error.

```
Set-AzureADUser : Error occurred while executing SetUser
Code: Service_InternalServerError
Message: Encountered an internal server error.
RequestId: xxxxxxx-312f-413d-86af-d062f627c630
DateTimeStamp: Tue, 02 Aug 2022 07:21:49 GMT
HttpStatusCode: InternalServerError
HttpStatusDescription: Internal Server Error
HttpResponseStatus: Completed
At line:1 char:1
+ Set-AzureADUser -ObjectId xxxxxxxxx-b488-4872-99cd-277668597e1a -Exten ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-AzureADUser], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.SetUser

```

**Comment by jmeddy** [comment]
I tried a few things for setting a blank ImmutableId value and finally got this one to work. It also avoids the "Set-MsolUser : Uniqueness violation. Property: SourceAnchor." error you would receive if trying to use a space or similar character more than once.

$var = ""
Set-MsolUser -UserPrincipalName user1@contoso.com -ImmutableId $var
Set-MsolUser -UserPrincipalName user2@contoso.com -ImmutableId $var

**Comment by polaran** [comment]
I tried this one and it worked for me:
Set-AzureADUser -ObjectId -Mobile ' '

**Comment by Borgquite** [comment]
@polaran FYI that's setting it to a single space, not to $null

We should all be using Graph now (see https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/833) and the old module won't be updated, I suspect. But if people insist, the best options I have found are:

`Remove-AzureADUserExtension -ObjectId "user@example.com" -ExtensionName "telephoneNumber"`

(NB despite the name, it clears the attribute value for a single user, not for all users - verified at https://stackoverflow.com/questions/61780722/remove-azureaduserextension-actual-result

or

```
$properties = [Collections.Generic.Dictionary[[String],[String]]]::new()
$properties.Add("telephoneNumber", [NullString]::Value)
Set-AzureADUser -ObjectId "user@example.com" -ExtensionProperty $properties
```

**Comment by yllekz** [comment]
While this doesn't excuse the lack of progress on this, This is a decent workaround:

```
$mguser = get-mguser -userid "person@mydomain.com"
Invoke-GraphRequest -Method PATCH -Uri "https://graph.microsoft.com/v1.0/Users/$($MgUser.UserPrincipalName)" -Body '{"OtherMails": []}'
```
