### ISSUE TITLE
Add-AzureADApplicationPolicy error

### ISSUE THREAD

**Issue by guylau** [Azure/azure-docs-powershell-azuread#95]
I am using AzureADPreview version 2.0.0.114 to associate token lifetime policy to an registered application using Add-AzureADApplicationPolicy, but got the following error:

_Open navigation properties are not supported on OpenTypes. Property name: 'policies'_ 

Any ideas?

Thank you.

**Comment by RobdeJong** [comment]
This is a known bug, we’re working on fixing it.

Thanks,

Rob

**Comment by RobdeJong** [comment]
This should be ficed in the current version of the module

**Comment by guylau** [comment]
Thanks.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by TaraMeyer** [comment]
@guylau - have you had a chance to confirm that it is indeed fixed in the current version?  Once I hear back from you, I will close this issue.  Thanks!

**Comment by guylau** [comment]
I install version 2.0.0.129, and did a quick test; unfortunately, I still get the same error. Is it possible to confirm which version I should use.

**Comment by TaraMeyer** [comment]
@RobdeJong - can you please confirm which version number this fix shipped in?

**Comment by slangley5150** [comment]
Just installed 2.0.0.129 and still get same error.

**Comment by philipWitherby** [comment]
@RobdeJong Yep, latest module installed and still the same issue. Any updates please?

Does mean that there is still a bug preventing ANY newly created policy to any object (in my case, an application registration)?

May we have an update on when we can expect any further fixes?

**Comment by samsterland** [comment]
Yay!  Installed 2.0.0.131 and Add-AzureADApplicationPolicy is now working!  Thank you.

**Comment by samsterland** [comment]
Correction, I installed 2.0.0.137 and Add-AzureADApplicationPolicy is now working!

**Comment by TaraMeyer** [comment]
That's great news @samsterland.  Nice work @RobdeJong!  I'm going to close this issue now.

**Comment by pilipicus** [comment]
Hi all,

I've created a web app. using as starting example this tutorial: https://docs.microsoft.com/en-us/outlook/rest/javascript-tutorial.
My application works without any problem on Microsoft Azure (azurewebsites.net) but now I have to change the token life until it's revoked (I would like that the token life never expires). In order to do this I've created my script following the current guide: https://docs.microsoft.com/en-us/azure/active-directory/active-directory-configurable-token-lifetimes.

The script that i've created for this policy is:

New-AzureADPolicy -Definition @('{"TokenLifetimePolicy":{"Version":1,"AccessTokenLifetime":"02:00:00","MaxAgeSessionSingleFactor":"02:00:00"}}') -DisplayName "WebPolicyScenario" -IsOrganizationDefault $false -Type "TokenLifetimePolicy"

It has been successfully created. However, when I try to apply it to my webapp I get the following error:

Add-AzureADApplicationPolicy : Error occurred while executing AddApplicationPolicy
Code: Request_BadRequest
Message: Policy operations on v2 application are disabled.
InnerError:
  RequestId: 7564################8bf0b9c
  DateTimeStamp: Thu, 22 Mar 2018 10:01:24 GMT
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed
At line:1 char:1
+ Add-AzureADApplicationPolicy -Id 9e29#################e5164df7 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-AzureADApplicationPolicy], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.MSGraphBeta.Client.ApiException,Microsoft.Open.MSGraphBeta.PowerShell.AddApplicationPolicy
 
The web app exists because if I run Get-AzureADApplication it's in the list with it's objectID.

Please help me to solve this problem.

I'm looking forward top hearing back from you.

**Comment by mtinnes** [comment]
Do the V2 apps not support custom token lifetime policies?

**Comment by didabel** [comment]
Je rencontre toujours le même problème.  y'a t-il une solution pour ça ?
